CREATE TABLE repos(
 id INTEGER NOT NULL PRIMARY KEY,
 name VARCHAR(100),
 url VARCHAR(100),
 language VARCHAR(100),
 description VARCHAR(255)
);


CREATE SEQUENCE se_repos
START WITH 1
INCREMENT BY 1;