-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 05:49:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ApiDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ApiDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ApiDB` DEFAULT CHARACTER SET utf8 ;
USE `ApiDB` ;

-- -----------------------------------------------------
-- Table `ApiDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ApiDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(95) NOT NULL,
  `Name` VARCHAR(95) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ApiDB`.`Repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ApiDB`.`Repository` (
  `idRepos` INT NOT NULL AUTO_INCREMENT,
  `repositoryQuantity` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idRepos`),
  INDEX `fk_Repository_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Repository_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ApiDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ApiDB`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ApiDB`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(95) NOT NULL,
  `projectLanguage` VARCHAR(15) NOT NULL,
  `projectReadme` VARCHAR(245) NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ApiDB`.`Project_has_Repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ApiDB`.`Project_has_Repository` (
  `Project_idProject` INT NOT NULL,
  `Repository_idRepos` INT NOT NULL,
  PRIMARY KEY (`Project_idProject`, `Repository_idRepos`),
  INDEX `fk_Project_has_Repository_Repository1_idx` (`Repository_idRepos` ASC) VISIBLE,
  INDEX `fk_Project_has_Repository_Project1_idx` (`Project_idProject` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_Repository_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `ApiDB`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_Repository_Repository1`
    FOREIGN KEY (`Repository_idRepos`)
    REFERENCES `ApiDB`.`Repository` (`idRepos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
