version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ateliware-challenge/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 1000
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root
