FROM elixir:1.11.2-alpine
  
RUN apk add --no-cache inotify-tools build-base git nodejs nodejs-npm

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force && \
    mkdir -p /umbrella

COPY . /umbrella
ENV MIX_ENV dev

RUN cd /umbrella && \
    mix do deps.get, compile && \
    npm install --prefix assets && \
    npm rebuild node-sass --prefix assets

WORKDIR /umbrella
EXPOSE 4000
CMD ["mix", "phx.server"]
