version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./production.Dockerfile
    image: facundoleites/dev-hiring-challenge
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7.37
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_TCP_PORT: "${MYSQL_PORT}"
    restart: on-failure
