# Generated by Django 4.0.3 on 2022-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gitrepo',
            name='stargazers_count',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
