# Generated by Django 4.0.3 on 2022-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_gitrepo_description_gitrepo_stargazers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='html_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
