# Generated by Django 4.0.1 on 2022-01-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
            options={
                'verbose_name': 'Linguagem',
                'verbose_name_plural': 'Linguagens',
                'db_table': 'linguagens',
            },
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('url', models.URLField()),
                ('estrelas', models.IntegerField()),
                ('pontos', models.FloatField()),
                ('acompanhadores', models.IntegerField()),
                ('lincenca', models.TextField()),
                ('descricao', models.TextField()),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.linguagem')),
            ],
            options={
                'verbose_name': 'Repositório',
                'verbose_name_plural': 'Repositórios',
                'db_table': 'repositorios',
            },
        ),
    ]
