# Generated by Django 4.0.1 on 2022-01-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
