# Generated by Django 4.0.1 on 2022-01-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositorio',
            old_name='lincenca',
            new_name='licenca',
        ),
    ]
