import Head from "next/head";
import React, { PropsWithChildren } from "react";
import { Footer } from "../Footer";
import { Header } from "../Header";
import styles from "./Layout.module.css";

interface LayoutProps {
  title: string;
  icon?: string;
}
export const Layout: React.FC<PropsWithChildren<LayoutProps>> = ({
  children,
  title,
  icon = "/favicon.ico",
}) => {
  return (
    <>
      <Head>
        <title>{`${title} - Prova Ateliware / Facundo Leites`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={icon} />
      </Head>
      <Header />
      <main className={`container ${styles.body}`}>{children}</main>
      <Footer />
    </>
  );
};
