version: 2.1

commands:
  build_project:
    description: "Generates jar"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew clean assemble
      - store_artifacts:
          path: build/libs/dev-hiring-challenge.jar
          destination: /home/circleci/dev-challenge/build/*

  execute_test:
    description: "Execute application tests"
    steps:
      - run: ./gradlew check
      - store_test_results:
          path: /home/circleci/dev-challenge/build/test-results/test
      - run:
          name: Code coverage
          command: |
            ./gradlew jacocoTestReport
            ./gradlew jacocoTestCoverageVerification
            bash <(curl -s https://codecov.io/bash)

jobs:
  build:
    working_directory: ~/dev-challenge
    docker:
      - image: circleci/openjdk:8
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - build_project
  test:
    working_directory: ~/dev-challenge
    docker:
      - image: circleci/openjdk:8
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - execute_test

workflows:
  "Project workflow":
    jobs:
      - build
      - test:
          requires:
            - build