# Generated by Django 3.0.7 on 2020-06-22 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('login', models.IntegerField()),
                ('html_url', models.CharField(max_length=200)),
                ('avatar_url', models.CharField(max_length=200)),
            ],
        ),
    ]
