# Generated by Django 3.0.7 on 2020-06-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Git_info',
        ),
    ]
