# Generated by Django 3.0.7 on 2020-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200622_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git_info',
            name='login',
            field=models.CharField(max_length=200),
        ),
    ]
