# Generated by Django 3.0.7 on 2020-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200622_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='git_info',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
    ]
