CREATE TABLE TB_REPOSITORIOS
(
	ID_NODE 					VARCHAR(150) PRIMARY KEY,
	ID 							INT,
	NOME_REPOSITORIO			NVARCHAR(250),
	NOME_COMPLETO_REPOSITORIO	NVARCHAR(MAX),
	LOGIN 						NVARCHAR(150),
	LINK_FOTO 					NVARCHAR(250)
)   

CREATE TABLE TB_LINGUAGEM
(
	ID_NODE 			VARCHAR(150),
	LOGIN 				NVARCHAR(150),
	LINK_FOTO 			NVARCHAR(250)
)