# Generated by Django 3.1.7 on 2021-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('stars', models.IntegerField(null=True)),
                ('forks', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=140)),
            ],
        ),
    ]
