# Generated by Django 3.1.1 on 2020-09-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(verbose_name='Linguagem')),
                ('name', models.TextField(verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('stars', models.TextField(verbose_name='Estrelas')),
                ('forks', models.TextField(verbose_name='Forks')),
                ('issues', models.TextField(verbose_name='Open Issues')),
                ('url', models.TextField(verbose_name='Endereço')),
            ],
        ),
    ]
