"""empty message

Revision ID: b5211abc05fc
Revises: 1a79047abb9a
Create Date: 2021-07-24 07:39:58.523995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5211abc05fc'
down_revision = '1a79047abb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repositories', sa.Column('stars', sa.Integer(), nullable=True))
    op.drop_column('Repositories', 'watchers')
    op.drop_column('Repositories', 'forks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repositories', sa.Column('forks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Repositories', sa.Column('watchers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Repositories', 'stars')
    # ### end Alembic commands ###
