# Generated by Django 3.0.7 on 2021-05-30 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Linguagem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Linguagem',
                'verbose_name_plural': 'Linguagens',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Repositório')),
                ('owner', models.CharField(max_length=100, verbose_name='Proprietário Login')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Salvo em')),
                ('size', models.IntegerField(default=0, verbose_name='Score')),
                ('url', models.URLField(max_length=100, verbose_name='Url')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Language')),
            ],
            options={
                'verbose_name': 'Repositório',
            },
        ),
    ]
