# Generated by Django 3.2.3 on 2021-05-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TbGitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100, unique=True)),
                ('repo_url', models.CharField(max_length=250)),
                ('repo_stars', models.IntegerField()),
                ('repo_commits', models.IntegerField()),
                ('repo_watchers', models.IntegerField()),
                ('repo_branches', models.IntegerField()),
                ('repo_forks', models.IntegerField()),
                ('repo_issues', models.IntegerField()),
                ('repo_up_at', models.DateTimeField()),
                ('id_fk_lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ateliware_git_app.tblanguages')),
            ],
        ),
    ]
