# Generated by Django 3.1 on 2020-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('language', models.CharField(max_length=255, verbose_name='language')),
                ('stars', models.IntegerField(default=0, verbose_name='stars')),
                ('watchers', models.IntegerField(default=0, verbose_name='watchers')),
                ('forks', models.IntegerField(default=0, verbose_name='forks')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('avatar_url', models.URLField(max_length=255, verbose_name='avatar_url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
                'ordering': ['pk', 'name', 'language'],
            },
        ),
    ]
