# Generated by Django 4.0.5 on 2022-06-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
