CREATE DATABASE ATELIWARE 
GO
USE ATELIWARE 
GO
CREATE TABLE [dbo].[TB_REPOSITORIO] 
(
    [ID_NODE]                   VARCHAR (150) NOT NULL,
    [ID]                        INT           NULL,
    [NOME_REPOSITORIO]          VARCHAR (250) NULL,
    [NOME_COMPLETO_REPOSITORIO] VARCHAR (MAX) NULL,
    [DESCRICAO_REPOSITORIO]     VARCHAR (MAX) NULL,
    [LINK_PUBLICO]              VARCHAR (250) NULL,
    [LOGIN]                     VARCHAR (150) NULL,
    [LINK_FOTO]                 VARCHAR (250) NULL,
    [URL_LINGUAGEM]             VARCHAR (150) NULL,
    PRIMARY KEY CLUSTERED ([ID_NODE] ASC)
);
GO
CREATE TABLE [dbo].[TB_REPOSITORIO_LINGUAGEM] (
    [ID_NODE]        VARCHAR (150) NOT NULL,
    [ID_LINGUAGEM]   INT           IDENTITY (1, 1) NOT NULL,
    [NOME_LINGUAGEM] VARCHAR (150) NULL,
    PRIMARY KEY CLUSTERED ([ID_NODE] ASC, [ID_LINGUAGEM] ASC),
    FOREIGN KEY ([ID_NODE]) REFERENCES [dbo].[TB_REPOSITORIO] ([ID_NODE])
);

