"""empty message

Revision ID: 76423362cc53
Revises: 6bafd3cebeab
Create Date: 2022-01-12 16:09:57.289246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76423362cc53'
down_revision = '6bafd3cebeab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'date')
    # ### end Alembic commands ###
