name: Build and Tests

on: [push]

jobs:

  build_and_test:

    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build with GO ${{ matrix.go-version }}
      run: go build -v ./...

    - name: Test with GO ${{ matrix.go-version }}
      run: go test -v ./...