# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:    
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./br/com/devhiringchallenge/backend 

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: changing directory
      run: ls -R
      working-directory: ${{env.working-directory}}
        
    - name: Installing node dependencies 
      run: |
        npm install
      working-directory: ${{env.working-directory}}
    
    - name: Running coverage test 
      run: |
        npm test
      working-directory: ${{env.working-directory}}
